### ISSUE TITLE
Requesting a new release as there have been a few changes since 0.1.0

### ISSUE THREAD

**Issue by strider-golang** [octokit/octopoller.rb#21]
We are happily using the 0.1.0 release and realized that there have been a few changes since, including [this](https://github.com/octokit/octopoller.rb/commit/750ccac493539cca9f4c7ea3ce80d43282c6046a).

I was just wondering if there is a plan for a 0.2.0 release any time soon?

Thanks!

**Comment by nickfloyd** [comment]
Hey @strider-golang, apologies for the delay on this, it's been a while.  We're working on cutting a new release of this right now.  I'll let you know when that's done if you're still interested.

**Comment by nickfloyd** [comment]
@strider-golang We just cut the [v0.2.0](https://github.com/octokit/octopoller.rb/releases/tag/v0.2.0) of this [gem](https://rubygems.org/gems/octopoller).  Let us know if anything comes up and thank you so much for the patience while we get things sorted out here!
