### ISSUE TITLE
[FEAT]: No wait

### ISSUE THREAD

**Issue by manuelmeurer** [octokit/octopoller.rb#39]
### Describe the need

I would like to retry something a few times with no wait in between, and therefore pass `wait: false` or `wait: 0` to the `poll` method.

Currently I get the error messages "Cannot wait backwards in time" or "undefined method `positive?' for false:FalseClass" when passing "0" or "false" as parameters, respectively.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manuelmeurer** [comment]
Happy to implement this as a feature btw. 😄

**Comment by nickfloyd** [comment]
Hey @manuelmeurer I think that would be a solid addition!

Work up a PR for this and I'd be glad to look over it and hopefully get it in!  Thanks for working to make octopoller and this community better ❤ !

**Comment by manuelmeurer** [comment]
Nice! Would you allow `false`, `0` or both as params?
